services:
  nodeseek-bot:
    build: .
    container_name: nodeseek-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
