services:
  nodeseek-bot:
    build:
      context: .
      network: host   # 👈 这里加上
    container_name: nodeseek-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
